### ISSUE TITLE
Unhelpful 500 error when user's assigned site_group has no sites

### ISSUE THREAD

**Issue by braddf** [openclimatefix/pv-site-api#115]
## Describe the bug
At the moment, the GET `/sites` endpoint with return a `500 Internal Server Error` when and if the user has no sites attached to their `site_group`. 

## To Reproduce
1. Sign in with a user account and assign a new and/or empty `site_group` to them in the user table;
2. Try to access the `/sites` endpoint via API or through the Quartz UI;
3. See `500 Internal Error` in console;
4. Also just `Assertion Error` in the logs I think, but fairly sure it's just because of the empty array.

## Expected behavior
I think should probably just return an empty array and leave this for people to handle this in kind when the response is received.

**Comment by peterdudfield** [comment]
I think there is Http response of 204, which might be useful here

**Comment by peterdudfield** [comment]
Ive removed this in #122 , as we might have no sites if the wrong filter is put in
