### ISSUE TITLE
Update sqlalamcy

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/pv-site-api#133]
Update sqlalamcy to latest (>2.0)

**Comment by peterdudfield** [comment]
this needs to be done here first - https://github.com/openclimatefix/pv-site-datamodel/issues/88

**Comment by roshnaeem** [comment]
Hello @peterdudfield, can i work on both of these issues, this one and https://github.com/openclimatefix/pv-site-datamodel/issues/88? Can you please assign me these?

**Comment by roshnaeem** [comment]
@peterdudfield, i am running pytest in this repository, and getting this error.

<img width="894" alt="Screenshot 2024-03-17 at 10 43 41 PM" src="https://github.com/openclimatefix/pv-site-api/assets/47316899/66f7a846-127d-4125-aae2-26c7d298fc49">

**Comment by peterdudfield** [comment]
Have you installed https://github.com/openclimatefix/pv-site-api/blob/main/pyproject.toml#L23 the dev dependecies?
