### ISSUE TITLE
Improve /pv_forecast documentation in API docs

### ISSUE THREAD

**Issue by zakwatts** [openclimatefix/pv-site-api#142]
1. The /sites/{site_uuid}/pv_forecast documentation is not reflective of what is actually pulled. (currently says 8-hours and every 30 mins when it is actually 36 hours and every 15 mins)

2. Also the example site_uuid of 567 does not work and as such does not return a sample forecast with the error:

```
"Failed to retrieve PV forecast data for site 567. Status code: 500
Response: Internal Server Error"
```

3. How to use /site/pv_forecast is not clear. An example of how to input multiple sites should be given.

**Comment by zakwatts** [comment]
1. is done by @peterdudfield

**Comment by peterdudfield** [comment]
Im dont think I've done 1

**Comment by zakwatts** [comment]
Sorry, my mistake.

**Comment by zakwatts** [comment]
4. make it clear that the expected_generation_kw is this a spot value and the datetime value is the forecast power at that exact time.

**Comment by peterdudfield** [comment]
> 4. make it clear that the expected_generation_kw is this a spot value and the datetime value is the forecast power at that exact time.

I think its actually the average power from that time to + 15 minutes. But yes we should make it clear

**Comment by peterdudfield** [comment]
#147 I think covers 1, 2, and 3
