### ISSUE TITLE
Save API requests

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/pv-site-api#154]
## Detailed Description
It would be good to save the api request and the username when each API call is made, and save it to a database

## Context
- similar to https://github.com/openclimatefix/uk-pv-national-gsp-api/blob/main/src/cache.py#L82

## Possible Implementation
In the cache function, add made in this issue - https://github.com/openclimatefix/pv-site-datamodel/issues/112
- add a test to check this value is written to the database

**Comment by mudrap17** [comment]
Hi @peterdudfield , I wanted to work on this issue and contribute to the GSoC projects! Would it possible to assign this issue to me?

**Comment by suleman1412** [comment]
Hi @peterdudfield, I had worked on the referred issue [pv-site-datamodel/issues/112](https://github.com/openclimatefix/pv-site-datamodel/issues/112) and I was confused whether to import the referred library or will this be from scratch?

**Comment by suleman1412** [comment]
hi @peterdudfield can I take this up if there aren't any updates?

**Comment by peterdudfield** [comment]
Merged in #161, but a test could be added to check that a api request is saved to the database when the api is called

**Comment by suleman1412** [comment]
Will the test involve just the function used to save api request, like [this](https://github.com/openclimatefix/pv-site-datamodel/blob/main/tests/test_write.py#L251)

**Comment by peterdudfield** [comment]
> Will the test involve just the function used to save api request, like [this](https://github.com/openclimatefix/pv-site-datamodel/blob/main/tests/test_write.py#L251)

yea, or could do something like [this](https://github.com/openclimatefix/uk-pv-national-gsp-api/blob/main/src/tests/test_status.py#L28)

**Comment by peterdudfield** [comment]
Just tested it locally, and the url seems to be blank. 

Would be great to add this to the test, and check `url is not None`. Maybe there is a small fix somewhere

**Comment by peterdudfield** [comment]
> Just tested it locally, and the url seems to be blank.
> 
> Would be great to add this to the test, and check `url is not None`. Maybe there is a small fix somewhere

We might need to add request to each api call, to make sure it goes through to the cache, https://github.com/openclimatefix/uk-pv-national-gsp-api/blob/main/src/gsp.py#L51C5-L51C22
