### ISSUE TITLE
Upgrade to sqlalchemy>2.0

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/pv-site-api#155]
## Detailed Description
This can be done using https://github.com/openclimatefix/pv-site-datamodel/issues/88
and pv-site-datamodel==1.0.17

## Context
- sqlalmacy upgrades should make things faster

## Possible Implementation
upgrade requirements and run tests

**Comment by rahul-maurya11b** [comment]
@peterdudfield sir please check #157 it solve errors which comes on updating the sqlalchemy >2.0 and please let me know If I have to create a separate PR based on current pv-site-api CI
