### ISSUE TITLE
edit site

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/pv-site-api#178]
## Detailed Description
similar to delete site, but a route to edit the site

## Context
- good for users to edit their site metadata

## Possible Implementation
- similar to https://github.com/openclimatefix/pv-site-api/issues/141, but put
- should take in a https://github.com/openclimatefix/pv-site-api/blob/main/pv_site_api/pydantic_models.py#L68
- https://github.com/openclimatefix/pv-site-api/blob/main/pv_site_api/main.py#L276
- Make sure the user has access to the site they are trying to edit

**Comment by Bvr4** [comment]
Hello, I'd like to be assigned to this issue if that's OK.

**Comment by peterdudfield** [comment]
Thank you @Bvr4

**Comment by BraunRudolf** [comment]
This is the same as #30 , right?

**Comment by peterdudfield** [comment]
> This is the same as #30 , right?

yea, thanks, Ive closed #30 now

**Comment by Bvr4** [comment]
Hello, to make this route, I think I should call a function like "update_site" from "pvsite_datamodel.write.user_and_site", isn't it ?

This function doesn't seem to exist at the moment.

**Comment by peterdudfield** [comment]
> Hello, to make this route, I think I should call a function like "update_site" from "pvsite_datamodel.write.user_and_site", isn't it ?
> 
> This function doesn't seem to exist at the moment.

Yea, im not sure it does. Might have to write it in their first

**Comment by peterdudfield** [comment]
This has mainly be done, just think we need to update the tag to 'Sites', then it will sit with the others

This should be done [here](https://github.com/openclimatefix/pv-site-api/blob/main/pv_site_api/main.py#L285)

like this

![Screenshot 2024-07-19 at 12 48 03](https://github.com/user-attachments/assets/80c4da5a-42cf-48cb-8638-95b831ae871a)


This is current api swagger

![Screenshot 2024-07-19 at 12 46 33](https://github.com/user-attachments/assets/a78328f3-395e-4f1f-8f47-a87feb688db6)

**Comment by Bvr4** [comment]
Indeed ! Sorry for the miss.

**Comment by zakwatts** [comment]
Closing this as now complete
