### ISSUE TITLE
Specify live data should be posted in Kilo Watts

### ISSUE THREAD

**Issue by zakwatts** [openclimatefix/pv-site-api#196]
Make it clearer to users that live data should be posted in KWs to avoid any confusion.

https://github.com/openclimatefix/pv-site-api/blob/e1741a78efbc6c122ffd8dc8f2f6c8993f67d4fa/pv_site_api/main.py#L237

**Comment by zakwatts** [comment]
Perhaps by updating the current function description to say: 

`Users will upload actual PV generation readings, in Kilo Watts, at regular intervals throughout a given day.

**Comment by peterdudfield** [comment]
![Screenshot 2024-10-01 at 13 56 59](https://github.com/user-attachments/assets/17eb8658-803c-4e82-96e7-c65029bcdfa9)

It current doesnt ahve kw in the variable name, but we should add more

**Comment by peterdudfield** [comment]
version 1.0.53
