### ISSUE TITLE
Add route for clear sky output 

### ISSUE THREAD

**Issue by ericcccsliu** [openclimatefix/pv-site-api#52]
## Detailed Description

Add a `GET` endpoint `/sites/{site_uuid}/clearsky` to return the clear sky outputs over the duration of the forecasts from `/sites/{site_uuid}/pv_forecast` 

## Context

For the [pv-sites-mobile](https://github.com/openclimatefix/pv-sites-mobile) project, we'd like to be able to compare forecasted outputs with the output of a clear sky. This information, when presented in a graph, will allow our users to easily contextualize the forecast for the upcoming day, giving a visual benchmark for the amount of solar power they'll receive. 

## Possible Implementation

1. add [pvlib](https://pvlib-python.readthedocs.io/en/stable/) as a dependency using `poetry`
2. add a `GET` endpoint `/sites/{site_uuid}/clearsky` 
3. retrieve site details using the `site_uuid` 
4. initialize a [`location`](https://pvlib-python.readthedocs.io/en/stable/reference/generated/pvlib.location.Location.html#pvlib-location-location) with pvlib, using relevant site details
5. get clear sky estimates of `ghi, dni, dhi` using the [`get_clearsky`](https://pvlib-python.readthedocs.io/en/stable/reference/generated/pvlib.location.Location.get_clearsky.html#pvlib.location.Location.get_clearsky) function
6. calculate total irradiance using the [`get_total_irradiance`](https://pvlib-python.readthedocs.io/en/stable/reference/generated/pvlib.irradiance.get_total_irradiance.html) function, using `surface_tilt` and `surface_azimuth` from our site details and passing in `solar_zenith` and `solar_azimuth` from the [`Location.get_solarposition`](https://pvlib-python.readthedocs.io/en/stable/reference/generated/pvlib.location.Location.get_solarposition.html) function
7. utilize total irradiance to calculate clear sky output and return 

Currently, we're not really clear on how to carry out that last step—specifically, calculating output from irradiance. We've looked into calculating output using [`pvlib.pvsystem.pvwatts_dc`](https://pvlib-python.readthedocs.io/en/stable/reference/pv_modeling/generated/pvlib.pvsystem.pvwatts_dc.html#pvlib.pvsystem.pvwatts_dc), but we're not sure about how to retrieve the required parameters associated with cell temperature.

**Comment by peterdudfield** [comment]
Ive deployed the new version, @ericcccsliu let me know if you are happy with the results

**Comment by ericcccsliu** [comment]
> Ive deployed the new version, @ericcccsliu let me know if you are happy with the results

Yep, it looks good to me!!!
