### ISSUE TITLE
Allow for differing module and inverter capacities

### ISSUE THREAD

**Issue by ericcccsliu** [openclimatefix/pv-site-api#54]
## Detailed Description

Instead of a single `installed_capacity_kw` field, allow for two different fields, representing the capacity of the inverter and the capacity of the solar panels. 

## Context

Right now, the API only allows for a site to have a single `installed_capacity_kw` field, storing the physical limit on the production capacity of the site. However, users might have different maximum capacities between their inverter and their solar panels. If allowing for differing capacities can lead to significantly more accurate estimates of PV production, it might be worth it to implement this change.

## Possible Implementation

Changes in this repository would likely be relatively trivial, but allowing for another field in the [pv-site-datamodel](https://github.com/openclimatefix/pv-site-datamodel) and adjusting predictions accordingly might be more difficult.

**Comment by peterdudfield** [comment]
Thanks @ericcccsliu , this is a great idea. Do you fancy doing this in here https://github.com/openclimatefix/pv-site-datamodel/blob/main/pvsite_datamodel/sqlmodels.py#L24? And making it optional. Then you can do the adjustments in this repo
