### ISSUE TITLE
Forecast route breaking on certain site_uuid(s)

### ISSUE THREAD

**Issue by braddf** [openclimatefix/pv-site-api#56]
## Describe the bug
Site `12e2d399-db22-45e6-a3f5-ff1a83498773` seems to cause an Internal Server Error when a forecast is requested

## To Reproduce
- Either on the single route:
   http://pvsite-development-api-sites.eu-west-1.elasticbeanstalk.com/sites/12e2d399-db22-45e6-a3f5-ff1a83498773/pv_forecast

- or the multi site route:
   http://pvsite-development-api-sites.eu-west-1.elasticbeanstalk.com/sites/pv_forecast?site_uuids=12e2d399-db22-45e6-a3f5-ff1a83498773

Calling the 53 site_uuids before this (in the order they come from API) is all good, getting actuals and forecasts.

## Expected behavior
Should return forecasts as the other sites do currently.

## Additional context
Initially found through Frontend UI calls, and then checked/confirmed through [Swagger](http://pvsite-development-api-sites.eu-west-1.elasticbeanstalk.com/swagger#/default/get_pv_forecast_sites__site_uuid__pv_forecast_get).

**Comment by simlmx** [comment]
For both queries I see this error in the logs:
```
2023-03-23T09:10:51.776-04:00 | nowcasting_api \| File "/app/./pv_site_api/_db_helpers.py", line 105, in _forecast_rows_to_pydantic
-- | --
  | 2023-03-23T09:10:51.776-04:00 | nowcasting_api \| SiteForecastValues(
  | 2023-03-23T09:10:51.776-04:00 | nowcasting_api \| File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
  | 2023-03-23T09:10:51.776-04:00 | nowcasting_api \| raise validation_error
  | 2023-03-23T09:10:51.776-04:00 | nowcasting_api \| pydantic.error_wrappers.ValidationError: 1 validation error for SiteForecastValues
  | 2023-03-23T09:10:51.776-04:00 | nowcasting_api \| expected_generation_kw
  | 2023-03-23T09:10:56.249-04:00 | nowcasting_api \| ensure this value is greater than or equal to 0 (type=value_error.number.not_ge; limit_value=0)
```
We restrict the values to "greater or equal to 0.". Maybe there is a rounding error? This should probably be a warning and we should clip it to 0.

I'll fix it!
