### ISSUE TITLE
When adding a site we always use the same client.

### ISSUE THREAD

**Issue by simlmx** [openclimatefix/pv-site-api#57]
# Description
When adding a new site, we always add it to the "first client", no matter which one it is. See:
https://github.com/openclimatefix/pv-site-api/blob/e5246fdba28d193d82216bed6ac06fa0cae393ba/pv_site_api/main.py#L200

This highlights some problems with our the route, namely that it doesn't accept a `client_uuid` at all.

This works now because we have only one client but could break as soon as someone adds another client in the DB.

# How to fix
* Make sure we pass in a `client_uuid` in the payload.
* Use that client instead of the `first` one.

# Other notes
The route is also confusing. ~~The REST way would be:
`PUT /sites` to add a new site and return the corresponding `site_uuid`.
`POST /sites/<site_uuid>` if the user wants to choose the `site_uuid` (which I'm not sure we want to do in general).~~
In a RESTful API, the id (`site_uuid`) should not be passed to the `POST` route, but returned by it.

**Comment by AndrewLester** [comment]
Hi @simlmx, while working on `pv-sites-mobile` we've looked into this too, so we appreciate you making this issue. One thing we were wondering is if this issue has implications on [Auth0 auth](https://github.com/openclimatefix/pv-site-api/issues/2#:~:text=Authorization%20user%20auth0), which is mentioned in a previous issue. This is also something we just talked about with @braddf earlier today.

@ericcccsliu and I were thinking that, if a user provides their Auth0 token, the API could identify the client in the database based on the token's session, or at least validate that the session has ownership over the client record (passed by the payload). The former option might require some additional database changes, but we haven't looked into it too closely yet. Just wanted to hear your thoughts, but we can also do some more investigation.

**Comment by simlmx** [comment]
Hey @AndrewLester ! Yes you are probably right that this route should be guarded by some authentication in general, but I'm not sure exactly what our plans are regarding authentication in the API in general. This discussion probably belongs in upcoming issues. Here I'm merely pointing out that there seems to be a big bug in our codebase!

**Comment by peterdudfield** [comment]
Thanks for raising this @simlmx  . 

We do plan to implement Auth0 soon. Perhaps in April. 

I think i agree with your idea @AndrewLester and @ericcccsliu. 

Steps would be
- Add Auth0
- add scopes, read access to sites / read access to national
- using auth0 session, either get client or make new client
- need to think about add sites to multi clients. I.e OCF users should have access to all Passive sites. Or 2 people from one company can see the sites. Might need to adjust the data model for this. We could make it a datamodel change with `users`, `client' and `sites`
-

**Comment by peterdudfield** [comment]
This is now solved with latest datamodel upgrade
