### ISSUE TITLE
Use the Database to generate Site UUIDs

### ISSUE THREAD

**Issue by AndrewLester** [openclimatefix/pv-site-api#62]
Use the database to generate Site UUIDs for new Sites instead of having an API consumer determine them. This makes sure collisions don't occur and also takes some work off the API consumer.

## Detailed Description

Use the database to generate Site UUIDs for new Sites created via this endpoint:
https://github.com/openclimatefix/pv-site-api/blob/01a5e21cd38f2cb656f6b98fa86554fafd2302ae/pv_site_api/main.py#L184

Hack4Impact is happy to take this work.

## Context

We'd like to use this endpoint to create sites in [`pv-sites-mobile`](https://github.com/openclimatefix/pv-sites-mobile), but we don't want to run into ID collisions (although rare), and generating them here will be easier for our implementation.

## Possible Implementation

The `SiteSQL` model in the `pv-site-datamodel` repo seems to already define a [default for the `site_uuid`](https://github.com/openclimatefix/pv-site-datamodel/blob/11080b34a3b893492ab2c7fd06fdb5ed0581f1c3/pvsite_datamodel/sqlmodels.py#L37) of a `SiteSQL` object, so SQLAlchemy will already do this for us it seems.

If I'm understanding correctly, that means that this line can just be deleted to support this:
https://github.com/openclimatefix/pv-site-api/blob/01a5e21cd38f2cb656f6b98fa86554fafd2302ae/pv_site_api/main.py#L200

With an additional deletion here:
https://github.com/openclimatefix/pv-site-api/blob/01a5e21cd38f2cb656f6b98fa86554fafd2302ae/pv_site_api/pydantic_models.py#L21-L24

**Alternatively, we can make submitting a UUID via the API optional to use that if it is available or a generated one otherwise (if using set UUIDs is already part of the site creation workflow)**

**Comment by simlmx** [comment]
This indeed makes a lot of sense. A PR doing what you described (not asking for a site_uuid and letting the DB generate one) would be welcome.

When we add a `GET /sites/<site_uuid>` route (we currently don't have one), perhaps we'll add back the `site_uuid` to pydantic model (if we want to reuse the same model), and make it optional to support both cases. Right now it's probably best to just remove it as you suggests.
